"""Add ImageTag model and relationship

Revision ID: 542e44c40c33
Revises: be9aab562a9d
Create Date: 2024-12-26 20:20:02.920197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542e44c40c33'
down_revision = 'be9aab562a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    op.execute("UPDATE analysis_result SET location = 'default_value' WHERE location IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
